# Generated by Django 4.1.3 on 2022-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadDocuments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
